In [3]:
import numpy as np

In [26]:
res = (np.array([0., 1. , 1. , 1. , 0., 1. , 0, 1. , 1. , 1. , 0., 0., 0., 0. , 1., 0., 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ]),
np.array([1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 0., 0., 0., 0., 0., 0., 0., 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ]))

In [27]:
res

(array([0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1.]))

In [28]:
res[0]

array([0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [29]:
res[1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1.])

In [40]:
def Recall(pre, lab):
    irre_lab = 0
    irre_pre = 0
    re_lab = 0
    re_pre = 0
    for i in range(0, len(lab)):
        if lab[i] == 0:
            irre_lab += 1
            if pre[i] == 0:
                irre_pre += 1
        else:
            re_lab += 1
            if lab[i] == 1:
                re_pre += 1
    irre_recall = irre_pre/irre_lab
    re_recall = re_pre/re_lab
    
    return (re_recall, irre_recall)

In [41]:
def Precision(pre, lab):
    irre_lab = 0
    irre_pre = 0
    re_lab = 0
    re_pre = 0
    for i in range(0, len(pre)):
        if pre[i] == 0:
            irre_pre += 1
            if lab[i] == 0:
                irre_lab += 1
        else:
            re_pre += 1
            if lab[i] == 1:
                re_lab += 1
    irre_precision = irre_lab/irre_pre
    re_precision = re_lab/re_pre
    
    return (re_precision, irre_precision)

In [42]:
Precision(res[0], res[1])

(0.8888888888888888, 0.7647058823529411)

In [36]:
Recall(res[0], res[1])

(1.0, 0.9285714285714286)